### ISSUE TITLE
Unable to install font on MacOS Seirra

### ISSUE THREAD

**Issue by vikxlp** [VanillaandCream/Palanquin#11]
FontBook doesn't let me install/use the font showing an ambiguous error.

Here is the screenshot:

<img width="610" alt="screenshot 2017-03-24 18 04 24" src="https://cloud.githubusercontent.com/assets/4686195/24294420/59cfbf98-10bc-11e7-8969-5075cb210a14.png">

**Comment by VanillaandCream** [comment]
Hi, click the box and go ahead with the installation. It should work. The
error message can show for various reasons like for instance you already
have the font installed in your system.

Best
Pria
